import Link from "next/link";
import "./globals.css";
import { Control } from "./Control";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const response = await fetch("http://localhost:9999/topics");
  const topics = await response.json();

  // console.log(topics);

  return (
    <html lang="en">
      <body>
        <div>
          <input type="text" placeholder="search" />
          <h1>
            <Link href="/"> WEB</Link>
          </h1>
          <ol>
            {/* {topics.map((topic) => {
              return <li key={topic.id}>{topic.title}</li>;
            })} */}
            {topics.map((topic) => (
              <li key={topic.id}>
                <Link href={`/read/${topic.id}`}>{topic.title}</Link>
              </li>
            ))}
          </ol>
          {children}
          <Control />
        </div>
      </body>
    </html>
  );
}
